name: 'Groove Music Client Dev Build'

on:
  push:
    branches:
      - develop
    paths:
        - 'client/**'
  workflow_dispatch:

permissions:
  id-token: write
  contents: read
      
jobs:
  client-build:
    name: Build and Push Client Docker Image
    runs-on: ubuntu-latest

    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      
      - name: Build Tag and push
        uses: docker/build-push-action@v5
        with:
          context: client
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/groove-music-client:dev-build-${{ github.run_number }}