name: 'Groove Music Prod Deployment'

on:
  push:
    branches:
      - main

permissions:
  id-token: write
  contents: read
      
jobs:
  client-build:
    runs-on: ubuntu-latest

    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      
      - name: Build and push tag
        uses: docker/build-push-action@v5
        with:
          context: "{{defaultContext}}:client"
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/groove-music-client:prod-build-${{ github.run_number }}
      
      - name: Build and push latest
        uses: docker/build-push-action@v5
        with:
          context: "{{defaultContext}}:client"
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/groove-music-client:latest
          
  server-build:
    runs-on: ubuntu-latest

    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      
      - name: Build and push tag
        uses: docker/build-push-action@v5
        with:
          context: "{{defaultContext}}:server"
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/groove-music-server:prod-build-${{ github.run_number }}
        
      - name: Build and push latest
        uses: docker/build-push-action@v5
        with:
          context: "{{defaultContext}}:server"
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/groove-music-server:latest